config/routes.rb
Rails.application.routes.draw do
  
  root   to: 'groups#index'
  
#static pages
  get 'help/*page_name', :controller => 'help', :action => 'help', :as => :help
#  get '/about', 	to: "static_pages#about"
#  get '/contact', 	to: "static_pages#contact"
  
  resources :parameters
  resources :groups
  devise_for :users
  resources :requests
  resources :audit_trails, :only=>[:index], :controller=>:audit_trails
  resources :keys 
  resources :users, :only=>[:new, :create, :edit, :update, :show, :index, :set_token, :pass, :destroy] do
    patch 'set_token', on: :member
    get 'pass', on: :member
  end
  get    '/api/:id/', to: 'keys#api'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string(100)      not null
#  code        :string(30)       not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  created_by  :string(100)
#  updated_by  :string(100)
#  is_active   :boolean          default(TRUE)
#

class Group < ApplicationRecord
#Filters
  before_save {self.code.upcase!}

#Record validations
  validates :name, :code, :created_by, :updated_by, presence: true
  validates :name, length: { minimum: 5, maximum: 100 }
  validates :code, length: { minimum: 3, maximum: 30 }
  validates :name, uniqueness: { case_sensitive: false }
  validates :code, uniqueness: { case_sensitive: false }

#Record relations
  has_many :users, :inverse_of => :group
  has_many :keys, :inverse_of => :group
  accepts_nested_attributes_for :keys, :reject_if => :all_blank, :allow_destroy => false
  validates_associated :keys
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.where("is_active = true").order(:code)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.created_by = current_user.user_name
    @group.updated_by = current_user.user_name
    @group.keys.each { |k| k.created_by = current_user.user_name }
    @group.keys.each { |k| k.updated_by = current_user.user_name}
    log_activity(@group.id, @group.name, request.env['REMOTE_ADDR'], 'na', 'na', 'Group created', false, false)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
def update
   @group.updated_by = current_user.user_name
   @group.keys.each { |k| k.updated_by = current_user.user_name}
   log_activity(@group.id, @group.name, request.env['REMOTE_ADDR'], 'na', 'na', 'Group updated', false, false)
   respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.is_active = false
    @group.updated_by = current_user.user_name
    @group.save
    log_activity(@group.id, @group.name, request.env['REMOTE_ADDR'], 'na', 'na', 'Group inactivated', false, false)
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully inactivated.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :code, :description, keys_attributes:[:user_id, :name, :description, :valid_from, :valid_until, :id])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
<div class="row">
  <div class="col-md-6">
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    </div>
   </div>

<div class="row">
  <div class="col-md-2 field_name">
    <%= t('Name') %> :
  </div>
  <div class="col-md-3 field">
    <%= f.text_field :name %>
  </div>
</div>

<div class="row">
  <div class="col-md-2 field_name">
    <%= t('Code') %> :
  </div>
  <div class="col-md-3 field">
    <%= f.text_field :code %>
  </div>
</div>

<div class="row">
  <div class="col-md-2 field_name">
    <%= t('Description') %> :
  </div>
  <div class="col-md-3 field">
    <%= f.text_area :description %>
  </div>
 </div>
  
<!-- should be displayed only if group udpate mode, and user is a keyAdmin role -->   	

  <div class="row">
    <div class="col-md-9 col-md-offset-1">
  <hr/>
  <h2> <%= t('KeysList') %> </h2>
      
  <table class="table table-striped">
    <tr>
      <th></th>
      <th><%= t('Responsible') %></th>
      <th><%= t('Key') %></th>
      <th><%= t('ValidFrom') %></th>
      <th><%= t('ValidTo') %></th>
      <th><%= t('Description') %></th>
    </tr>
		<% if can? :update, Key %> 
			<%=  f.nested_fields_for :keys, wrapper_tag: 'tr' do |cipher| %>
				<td> <%= cipher.remove_nested_fields_link {image_tag("remove.png")} %></td>
				<td> <%= cipher.collection_select :user_id, data_owners_list, :id, :user_name %> </td> 
				<td> <%= cipher.text_field :name %> </td>
				<td> <%= cipher.date_field :valid_from %> </td>
				<td> <%= cipher.date_field :valid_until %> </td>
				<td> <%= cipher.text_area :description %> </td>
			<% end %>
		<% else %>
			<% group.keys.each do |cipher| %>
   <tr>
     <td> </td>
     <td> <%= cipher.user.name %> </td>
     <td> <%= cipher.name %> </td>
     <td> <%= cipher.valid_from %> </td>
     <td> <%= cipher.valid_until %> </td>
     <td> <%= cipher.description %> </td>
   </tr>

			<% end %>
		<% end %>

  </table>
 
	<% if can? :create, Key %>  
		<%= f.add_nested_fields_link :keys, image_tag("add.png") %> <%= t('New') %> 
	<% end %>

  </div>
  </div>   	
		<div class="row">
			<div class="col-md-4 col-md-offset-1">
		<div class="actions">
    <%= f.submit t('Validate')%>
  </div>

  </div>
</div>
  
<% end %>

app/views/groups/edit.html.erb
<h1><%=t('EditGroup')%></h1>

<%= render 'form', group: @group %>

<%= link_to t('Show'), @group %> |
<%= link_to t('Back'), groups_path %>

app/views/groups/index.html.erb
<h1><%=t('Groups') %> </h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Code') %></th>
      <th><%= t('Description') %></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group %></td>
        <td><%= group.code %></td>
        <td><%= group.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('NewGroup'), new_group_path %>

app/views/groups/new.html.erb
<h1><%=t('NewGroup')%></h1>

<%= render 'form', group: @group %>

<%= link_to t('Back'), groups_path %>

app/views/groups/show.html.erb
<h1> <%= t('Group') %> <%= @group.name %> </h1>

<div class="row">
  <div class="col-md-2 field_name">
    <%= t('Name') %> :
  </div>
  <div class="col-md-3 field">
    <%= @group.name %>
  </div>
</div>

<div class="row">
  <div class="col-md-2 field_name">
    <%= t('Code') %> :
  </div>
  <div class="col-md-3 field">
    <%= @group.code %>
  </div>
</div>

<div class="row">
  <div class="col-md-2 field_name">
    <%= t('Description') %> :
  </div>
  <div class="col-md-3 field">
    <%= @group.description %>
  </div>
</div>

<br/>

  <div class="tabbable">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#keys" data-toggle="tab"> <%= t('KeysList') %> </a></li>
      <li><a href="#users" data-toggle="tab"> <%= t('GroupUsers') %> </a></li>
    </ul>
    
    <div class="tab-content">
      
      <div class="tab-pane active" id="keys">
        <table class="table table-striped table-condensed">
          <tr align="left">
            <th></th>
            <th><%= t('ObjectId') %></th>
            <th><%= t('Name') %></th>
            <th><%= t('Responsible') %></th>
            <th><%= t('ValidFrom') %></th>
            <th><%= t('ValidTo') %></th>
            <th><%= t('UpdatedBy') %></th>
            <th><%= t('UpdatedAt') %></th>
          </tr>
          
          <% @group.keys.order("updated_at").each do |child_object| %>
          <tr align="left">
            <td><%= link_to image_tag("lock16.png"), edit_key_path(child_object) %> </a></td>
            <td valign="top"> <%=child_object.id%> </td>
            <td valign="top"> <%=child_object.name%> </td>
            <td valign="top"> <%=child_object.user.first_name + ' ' + child_object.user.name %> </td>
            <td valign="top"> <%=child_object.valid_from%> </td>
            <td valign="top"> <%=child_object.valid_until%> </td>
            <td valign="top"> <%=child_object.updated_by%> </td>
            <td valign="top"> <%=child_object.updated_at%> </td>
          </tr>
          <% end%>
        </table>
      </div>
    
      <div class="tab-pane" id="users">
        <table class="table table-striped table-condensed">
          <tr align="left">
            <th><%= t('FirstName') %></th>
            <th><%= t('Name') %></th>
            <th><%= t('Role') %></th>
            <th><%= t('Section') %></th>
            <th><%= t('UpdatedBy') %></th>
            <th><%= t('UpdatedAt') %></th>
          </tr>
          
          <% @group.users.order("name").each do |child_object| %>
          <tr align="left">
            <td valign="top"> <%=child_object.first_name %> </td>
            <td valign="top"> <%=child_object.name %> </td>
            <td valign="top"> <%=child_object.role.name %> </td>
            <td valign="top"> <%=child_object.section %> </td>
            <td valign="top"> <%=child_object.updated_by%> </td>
            <td valign="top"> <%=child_object.updated_at%> </td>
          </tr>
          <% end%>
        </table>
      </div>
      
    </div>
  </div>
  
<%= link_to t('EditGroup'), edit_group_path(@group) %> |
<%= link_to t('Back'), groups_path %> | 
<%= link_to t('Delete'), @group, confirm: t('Sure'), method: :delete %>