config/routes.rb
Rails.application.routes.draw do
  
  root   to: 'groups#index'
  
#static pages
  get 'help/*page_name', :controller => 'help', :action => 'help', :as => :help
#  get '/about', 	to: "static_pages#about"
#  get '/contact', 	to: "static_pages#contact"
  
  resources :parameters
  resources :groups
  devise_for :users
  resources :requests
  resources :audit_trails, :only=>[:index], :controller=>:audit_trails
  resources :keys 
  resources :users, :only=>[:new, :create, :edit, :update, :show, :index, :set_token, :pass, :destroy] do
    patch 'set_token', on: :member
    get 'pass', on: :member
  end
  get    '/api/:id/', to: 'keys#api'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=t('CKManager')%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <div class="flex-container-v">
		<div class="flex-container">
			<div class="flex-item-border logo">
				<br/>
				<%= image_tag("k.png", alt: "KeyMan") %>
				<%= $VERSION %>
				<br/>
			</div>
			<div class="flex-item">
				<div class="col-md-6">
					<h1><%= t('CKManager') %></h1>
				</div>
				<div class="col-md-6">
					<div class="row">
						<nav class="top_menu">
							<ul>
								<% if user_signed_in? %>
									<% if can? :renew_token, current_user %>
                    <li> <button id="key_toggle">K</button> </li>
                  <% end %>
									<li> <%= t('UserName') %>: <%= link_to (current_user.first_name + ' ' + current_user.name), pass_user_path(current_user) %></li>
									<li> | <%= link_to t('Sign_out'), destroy_user_session_path, method: "delete" %></li>
								<% else %>
									<li> <%= link_to t('Sign_in'), new_user_session_path %></li>
								<% end %>
								<li> | <%= link_to t('Help'), help_path("help-index") %> </li>
							</ul>
						</nav>
					</div>
					<div class="row" id="renew_token">
						<nav class="top_menu">
							<% if user_signed_in? %>
								<!-- token generation form -->
								<%= form_for(current_user, url: set_token_user_path(current_user), method: :patch) do |f| %>
									<% if current_user.errors.any? %>
										<div id="error_explanation">
										<h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>
											<ul>
											<% current_user.errors.full_messages.each do |message| %>
												<li><%= message %></li>
											<% end %>
											</ul>
										</div>
									<% end %>
									<ul>
										<li><%= t('Token') %>: <%= f.text_field :authentication_token, :size => "16", readonly: true %> </li>
										<li><%= t('Count') %>: <%= f.text_field :api_token_count, :size => "4" %> </li>
										<li><%= t('Validity') %>: <%= f.date_field :api_token_validity, :size => "10" %> </li>
										<li class="actions" ><%= f.submit t('Renew') %></li>
									</ul>
								<% end %>
							<% end %>
						</vav>
					</div>
				</div>
			</div>
		</div>
		<div class="flex-container">
			<div class="flex-item-border">
				<div class="row">
					<div class="col-md-2">
						<h1>
						K
						E
						Y
						M
						A
						N
						</h1>
					</div>
					<div class="col-md-3">
						<ul class="side_menu" role="menu">
							<br/><br/>
							<li><%= link_to t('Groups'), groups_path %></li>
							<li><%= link_to t('Users'), users_path %></li>
							<li><%= link_to t('Parameters'), parameters_path %></li>
							<li><%= link_to t('Audit'), audit_trails_path %></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="flex-item">
				<div class="container-fluid">
					<%= yield %>							
				</div>
			</div>
		</div>
		<div class="flex-item">
			<% if notice %>
				<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
				<p class="alert alert-danger"><%= alert %></p>
			<% end %>
		</div>
		<div class="flex-item">
		  <a class="top_menu" href="http://opendataquality.com">Open Data Quality</a>
		</div>
	</div>

	<script> $(function() {
		$( "#key_toggle" ).click(function() {
			$( "#renew_token" ).toggle();
			});
		});
	</script>

  </body>

  <%= debug(params) if Rails.env.development? %>
  
</html>