config/routes.rb
Rails.application.routes.draw do
  
  root   to: 'groups#index'
  
#static pages
  get 'help/*page_name', :controller => 'help', :action => 'help', :as => :help
#  get '/about', 	to: "static_pages#about"
#  get '/contact', 	to: "static_pages#contact"
  
  resources :parameters
  resources :groups
  devise_for :users
  resources :requests
  resources :audit_trails, :only=>[:index], :controller=>:audit_trails
  resources :keys 
  resources :users, :only=>[:new, :create, :edit, :update, :show, :index, :set_token, :pass, :destroy] do
    patch 'set_token', on: :member
    get 'pass', on: :member
  end
  get    '/api/:id/', to: 'keys#api'

end

app/models/parameter.rb
# == Schema Information
#
# Table name: parameters
#
#  id          :integer          not null, primary key
#  name        :string(100)      not null
#  list_name   :string(100)
#  description :text
#  code        :string(30)       not null
#  value       :string(100)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  created_by  :string(100)
#  updated_by  :string(100)
#

class Parameter < ApplicationRecord
    
#Validations
  validates :name, :code, presence: true
  validates :name, length: { minimum: 5, maximum: 100 }
  validates :code, length: { minimum: 1, maximum: 30 }
  validates :name, uniqueness: {case_sensitive: false }
  validates :code, uniqueness: {case_sensitive: false }
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_parameter, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /parameters
  # GET /parameters.json
  def index
    @parameters = Parameter.where("is_active=true") 
  end

  # GET /parameters/1
  # GET /parameters/1.json
  def show
  end

  # GET /parameters/new
  def new
    @parameter = Parameter.new
  end

  # GET /parameters/1/edit
  def edit
  end

  # POST /parameters
  # POST /parameters.json
  def create
    @parameter = Parameter.new(parameter_params)
    log_activity(@parameter.id, @parameter.name, request.env['REMOTE_ADDR'], 'na', 'na', 'Parameter created', false, false)
    respond_to do |format|
      if @parameter.save
        format.html { redirect_to @parameter, notice: 'Parameter was successfully created.' }
        format.json { render :show, status: :created, location: @parameter }
      else
        format.html { render :new }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parameters/1
  # PATCH/PUT /parameters/1.json
  def update
    log_activity(@parameter.id, @parameter.name, request.env['REMOTE_ADDR'], 'na', 'na', 'Parameter updated', false, false)
    respond_to do |format|
      if @parameter.update(parameter_params)
        format.html { redirect_to @parameter, notice: 'Parameter was successfully updated.' }
        format.json { render :show, status: :ok, location: @parameter }
      else
        format.html { render :edit }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parameters/1
  # DELETE /parameters/1.json
  def destroy
    @parameter.is_active = false
    @parameter.updated_by = current_user.user_name
    @parameter.save
    log_activity(@parameter.id, @parameter.name, request.env['REMOTE_ADDR'], 'na', 'na', 'Parameter deleted', false, false)
    respond_to do |format|
      format.html { redirect_to parameters_url, notice: 'Parameter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parameter
      @parameter = Parameter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parameter_params
      params.require(:parameter).permit(:name, :description, :code, :value, :list_name)
    end
end

app/helpers/parameters_helper.rb
module ParametersHelper
  
    def get_roles_list
        roles_list = Parameter.select("id, name").where("is_active=true and list_name=?",'Roles')
    end

    def get_initial_roles_list
        roles_list = Parameter.select("id, name").where("id=?",'0')
    end
 
    def get_parameters_lists
        lists_list = Parameter.select("id, name, value").where("list_name=?",'All lists')
    end
    
    def get_sections_list
        sections_list = Parameter.select("id, name, value").where("list_name=?",'Sections')
    end
    
    def get_keysizes_list
        keysizes_list = Parameter.select("id, name").where("list_name=?",'Key Sizes')
    end

end

app/views/parameters/_form.html.erb
<%= form_for(parameter) do |f| %>
  <% if parameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parameter.errors.count, "error") %> prohibited this parameter from being saved:</h2>

      <ul>
      <% parameter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('Name') %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label t('Description') %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label t('Code') %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label t('Value') %>
    <%= f.text_field :value %>
  </div>

  <div class="field">
    <%= f.label t('ListName') %>
    <%= f.collection_select :list_name, get_parameters_lists, :value, :name %>
  </div>
  <br/>

  <div class="actions">
    <%= f.submit t('Validate')%>
  </div>
<% end %>

app/views/parameters/edit.html.erb
<h1><%= t('EditParameter') %></h1>

<%= render 'form', parameter: @parameter %>

<%= link_to t('Show'), @parameter %> |
<%= link_to t('Back'), parameters_path %>

app/views/parameters/index.html.erb
<h1><%= t('Parameters') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('Name')%></th>
      <th><%= t('Description')%></th>
      <th><%= t('Code')%></th>
      <th><%= t('Value')%></th>
      <th><%= t('List')%></th>
      <th colspan=2><%= t('Actions')%></th>
    </tr>
  </thead>

  <tbody>
    <% @parameters.order(:list_name).each do |parameter| %>
      <tr>
        <td><%= parameter.name %></td>
        <td><%= parameter.description %></td>
        <td><%= parameter.code %></td>
        <td><%= parameter.value %></td>
        <td><%= parameter.list_name %></td>
<!--    <td><%= link_to 'Show', parameter %></td> -->
        <td><%= link_to t('Edit'), edit_parameter_path(parameter) %></td>
        <td><%= link_to t('Inactivate'), parameter, method: :delete, data: { confirm: t('Sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('NewParameter'), new_parameter_path %>

app/views/parameters/new.html.erb
<h1><%= t('NewParameter') %></h1>

<%= render 'form', parameter: @parameter %>

<%= link_to t('Back'), parameters_path %>

app/views/parameters/show.html.erb
<p>
  <strong><%= t('Name')%></strong>
  <%= @parameter.name %>
</p>

<p>
  <strong><%= t('Description')%></strong>
  <%= @parameter.description %>
</p>

<p>
  <strong><%= t('Code')%></strong>
  <%= @parameter.code %>
</p>

<p>
  <strong><%= t('Value')%></strong>
  <%= @parameter.value %>
</p>

<p>
  <strong><%= t('List name')%></strong>
  <%= @parameter.list_name %>
</p>


<%= link_to t('Edit'), edit_parameter_path(@parameter) %> |
<%= link_to t('Back'), parameters_path %>